#! /usr/bin/env python3

import os

commands = [
  'python3 maian.py -s example_contracts/example_suicidal.sol KAI -c 0',
  'python3 maian.py -b example_contracts/example_suicidal.bytecode -c 0',
  'python3 maian.py -bs example_contracts/example_suicidal.bytecode_source -c 0',
  'python3 maian.py -s example_contracts/example_prodigal.sol Adoption -c 1',
  'python3 maian.py -b example_contracts/example_prodigal.bytecode -c 1',
  'python3 maian.py -bs example_contracts/example_prodigal.bytecode_source -c 1',
  'python3 maian.py -b example_contracts/example_greedy.bytecode -c 2',
  'python3 maian.py -s example_contracts/ParityWalletLibrary.sol WalletLibrary -c 0'
]
for cmd in commands:
  m = len(cmd) + len("Running: ")
  print("*"*m)
  print("Running:",cmd)
  print("*"*m)
  os.system(cmd)

